// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: protofiles/checkbookpb/checkbook.proto

package checkbook

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pages int32

const (
	Pages_PAGES_UNSPECIFIED Pages = 0
	Pages_TWENTY_FIVE       Pages = 1
	Pages_FIFTY             Pages = 2
)

// Enum value maps for Pages.
var (
	Pages_name = map[int32]string{
		0: "PAGES_UNSPECIFIED",
		1: "TWENTY_FIVE",
		2: "FIFTY",
	}
	Pages_value = map[string]int32{
		"PAGES_UNSPECIFIED": 0,
		"TWENTY_FIVE":       1,
		"FIFTY":             2,
	}
)

func (x Pages) Enum() *Pages {
	p := new(Pages)
	*p = x
	return p
}

func (x Pages) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Pages) Descriptor() protoreflect.EnumDescriptor {
	return file_protofiles_checkbookpb_checkbook_proto_enumTypes[0].Descriptor()
}

func (Pages) Type() protoreflect.EnumType {
	return &file_protofiles_checkbookpb_checkbook_proto_enumTypes[0]
}

func (x Pages) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Pages.Descriptor instead.
func (Pages) EnumDescriptor() ([]byte, []int) {
	return file_protofiles_checkbookpb_checkbook_proto_rawDescGZIP(), []int{0}
}

type CheckbookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NbPage    Pages  `protobuf:"varint,1,opt,name=nbPage,proto3,enum=protofiles.Pages" json:"nbPage,omitempty"`
	AccountId string `protobuf:"bytes,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
}

func (x *CheckbookRequest) Reset() {
	*x = CheckbookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_checkbookpb_checkbook_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckbookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckbookRequest) ProtoMessage() {}

func (x *CheckbookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_checkbookpb_checkbook_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckbookRequest.ProtoReflect.Descriptor instead.
func (*CheckbookRequest) Descriptor() ([]byte, []int) {
	return file_protofiles_checkbookpb_checkbook_proto_rawDescGZIP(), []int{0}
}

func (x *CheckbookRequest) GetNbPage() Pages {
	if x != nil {
		return x.NbPage
	}
	return Pages_PAGES_UNSPECIFIED
}

func (x *CheckbookRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type CheckbookResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NbPage       Pages                  `protobuf:"varint,1,opt,name=nbPage,proto3,enum=protofiles.Pages" json:"nbPage,omitempty"`
	AccountId    string                 `protobuf:"bytes,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
	CreationDate *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=creationDate,proto3" json:"creationDate,omitempty"`
	Id           int32                  `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CheckbookResponse) Reset() {
	*x = CheckbookResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_checkbookpb_checkbook_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckbookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckbookResponse) ProtoMessage() {}

func (x *CheckbookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_checkbookpb_checkbook_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckbookResponse.ProtoReflect.Descriptor instead.
func (*CheckbookResponse) Descriptor() ([]byte, []int) {
	return file_protofiles_checkbookpb_checkbook_proto_rawDescGZIP(), []int{1}
}

func (x *CheckbookResponse) GetNbPage() Pages {
	if x != nil {
		return x.NbPage
	}
	return Pages_PAGES_UNSPECIFIED
}

func (x *CheckbookResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CheckbookResponse) GetCreationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationDate
	}
	return nil
}

func (x *CheckbookResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CheckbookList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Checkbooks []*CheckbookResponse `protobuf:"bytes,1,rep,name=checkbooks,proto3" json:"checkbooks,omitempty"`
}

func (x *CheckbookList) Reset() {
	*x = CheckbookList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_checkbookpb_checkbook_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckbookList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckbookList) ProtoMessage() {}

func (x *CheckbookList) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_checkbookpb_checkbook_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckbookList.ProtoReflect.Descriptor instead.
func (*CheckbookList) Descriptor() ([]byte, []int) {
	return file_protofiles_checkbookpb_checkbook_proto_rawDescGZIP(), []int{2}
}

func (x *CheckbookList) GetCheckbooks() []*CheckbookResponse {
	if x != nil {
		return x.Checkbooks
	}
	return nil
}

type AccountId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
}

func (x *AccountId) Reset() {
	*x = AccountId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_checkbookpb_checkbook_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountId) ProtoMessage() {}

func (x *AccountId) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_checkbookpb_checkbook_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountId.ProtoReflect.Descriptor instead.
func (*AccountId) Descriptor() ([]byte, []int) {
	return file_protofiles_checkbookpb_checkbook_proto_rawDescGZIP(), []int{3}
}

func (x *AccountId) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

var File_protofiles_checkbookpb_checkbook_proto protoreflect.FileDescriptor

var file_protofiles_checkbookpb_checkbook_proto_rawDesc = []byte{
	0x0a, 0x26, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x62, 0x6f, 0x6f, 0x6b, 0x70, 0x62, 0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x62, 0x6f,
	0x6f, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5b, 0x0a, 0x10, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x62, 0x6f,
	0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x06, 0x6e, 0x62, 0x50,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x73, 0x52, 0x06, 0x6e, 0x62,
	0x50, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x64, 0x22, 0xac, 0x01, 0x0a, 0x11, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x62, 0x6f, 0x6f, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x6e, 0x62, 0x50, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x73, 0x52, 0x06, 0x6e, 0x62, 0x50,
	0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x3e, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x4e, 0x0a, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x62, 0x6f, 0x6f, 0x6b, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x3d, 0x0a, 0x0a, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x62, 0x6f, 0x6f, 0x6b, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x62, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0a, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x62, 0x6f, 0x6f, 0x6b,
	0x73, 0x22, 0x29, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x2a, 0x3a, 0x0a, 0x05,
	0x50, 0x61, 0x67, 0x65, 0x73, 0x12, 0x15, 0x0a, 0x11, 0x50, 0x41, 0x47, 0x45, 0x53, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b,
	0x54, 0x57, 0x45, 0x4e, 0x54, 0x59, 0x5f, 0x46, 0x49, 0x56, 0x45, 0x10, 0x01, 0x12, 0x09, 0x0a,
	0x05, 0x46, 0x49, 0x46, 0x54, 0x59, 0x10, 0x02, 0x32, 0xa5, 0x01, 0x0a, 0x10, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x62, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4e, 0x0a,
	0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x62, 0x6f, 0x6f, 0x6b,
	0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x62, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x62, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x12, 0x15,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x49, 0x64, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x73, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x62, 0x6f, 0x6f, 0x6b, 0x4c, 0x69, 0x73, 0x74,
	0x42, 0x29, 0x5a, 0x27, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x74, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x2f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x62, 0x6f, 0x6f, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_protofiles_checkbookpb_checkbook_proto_rawDescOnce sync.Once
	file_protofiles_checkbookpb_checkbook_proto_rawDescData = file_protofiles_checkbookpb_checkbook_proto_rawDesc
)

func file_protofiles_checkbookpb_checkbook_proto_rawDescGZIP() []byte {
	file_protofiles_checkbookpb_checkbook_proto_rawDescOnce.Do(func() {
		file_protofiles_checkbookpb_checkbook_proto_rawDescData = protoimpl.X.CompressGZIP(file_protofiles_checkbookpb_checkbook_proto_rawDescData)
	})
	return file_protofiles_checkbookpb_checkbook_proto_rawDescData
}

var file_protofiles_checkbookpb_checkbook_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protofiles_checkbookpb_checkbook_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protofiles_checkbookpb_checkbook_proto_goTypes = []interface{}{
	(Pages)(0),                    // 0: protofiles.Pages
	(*CheckbookRequest)(nil),      // 1: protofiles.CheckbookRequest
	(*CheckbookResponse)(nil),     // 2: protofiles.CheckbookResponse
	(*CheckbookList)(nil),         // 3: protofiles.CheckbookList
	(*AccountId)(nil),             // 4: protofiles.AccountId
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_protofiles_checkbookpb_checkbook_proto_depIdxs = []int32{
	0, // 0: protofiles.CheckbookRequest.nbPage:type_name -> protofiles.Pages
	0, // 1: protofiles.CheckbookResponse.nbPage:type_name -> protofiles.Pages
	5, // 2: protofiles.CheckbookResponse.creationDate:type_name -> google.protobuf.Timestamp
	2, // 3: protofiles.CheckbookList.checkbooks:type_name -> protofiles.CheckbookResponse
	1, // 4: protofiles.CheckbookService.CreateCheckbook:input_type -> protofiles.CheckbookRequest
	4, // 5: protofiles.CheckbookService.GetCheckbooks:input_type -> protofiles.AccountId
	2, // 6: protofiles.CheckbookService.CreateCheckbook:output_type -> protofiles.CheckbookResponse
	3, // 7: protofiles.CheckbookService.GetCheckbooks:output_type -> protofiles.CheckbookList
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protofiles_checkbookpb_checkbook_proto_init() }
func file_protofiles_checkbookpb_checkbook_proto_init() {
	if File_protofiles_checkbookpb_checkbook_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protofiles_checkbookpb_checkbook_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckbookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_checkbookpb_checkbook_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckbookResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_checkbookpb_checkbook_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckbookList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_checkbookpb_checkbook_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protofiles_checkbookpb_checkbook_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protofiles_checkbookpb_checkbook_proto_goTypes,
		DependencyIndexes: file_protofiles_checkbookpb_checkbook_proto_depIdxs,
		EnumInfos:         file_protofiles_checkbookpb_checkbook_proto_enumTypes,
		MessageInfos:      file_protofiles_checkbookpb_checkbook_proto_msgTypes,
	}.Build()
	File_protofiles_checkbookpb_checkbook_proto = out.File
	file_protofiles_checkbookpb_checkbook_proto_rawDesc = nil
	file_protofiles_checkbookpb_checkbook_proto_goTypes = nil
	file_protofiles_checkbookpb_checkbook_proto_depIdxs = nil
}
