// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v7.34.1
// source: checkbook.proto

package checkbook

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckbookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NbPage       int32  `protobuf:"varint,1,opt,name=nbPage,proto3" json:"nbPage,omitempty"`
	AccountId    string `protobuf:"bytes,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
	CreationDate string `protobuf:"bytes,3,opt,name=creationDate,proto3" json:"creationDate,omitempty"`
}

func (x *CheckbookRequest) Reset() {
	*x = CheckbookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_checkbook_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckbookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckbookRequest) ProtoMessage() {}

func (x *CheckbookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_checkbook_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckbookRequest.ProtoReflect.Descriptor instead.
func (*CheckbookRequest) Descriptor() ([]byte, []int) {
	return file_checkbook_proto_rawDescGZIP(), []int{0}
}

func (x *CheckbookRequest) GetNbPage() int32 {
	if x != nil {
		return x.NbPage
	}
	return 0
}

func (x *CheckbookRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CheckbookRequest) GetCreationDate() string {
	if x != nil {
		return x.CreationDate
	}
	return ""
}

type CheckbookResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NbPage       int32  `protobuf:"varint,1,opt,name=nbPage,proto3" json:"nbPage,omitempty"`
	AccountId    string `protobuf:"bytes,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
	CreationDate string `protobuf:"bytes,3,opt,name=creationDate,proto3" json:"creationDate,omitempty"`
	Id           int32  `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CheckbookResponse) Reset() {
	*x = CheckbookResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_checkbook_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckbookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckbookResponse) ProtoMessage() {}

func (x *CheckbookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_checkbook_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckbookResponse.ProtoReflect.Descriptor instead.
func (*CheckbookResponse) Descriptor() ([]byte, []int) {
	return file_checkbook_proto_rawDescGZIP(), []int{1}
}

func (x *CheckbookResponse) GetNbPage() int32 {
	if x != nil {
		return x.NbPage
	}
	return 0
}

func (x *CheckbookResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CheckbookResponse) GetCreationDate() string {
	if x != nil {
		return x.CreationDate
	}
	return ""
}

func (x *CheckbookResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_checkbook_proto protoreflect.FileDescriptor

var file_checkbook_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x6c, 0x0a,
	0x10, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x62, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x62, 0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x6e, 0x62, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x22, 0x7d, 0x0a, 0x11, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x62, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x6e, 0x62, 0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x6e, 0x62, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x32, 0x64, 0x0a, 0x10, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x62, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50,
	0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x62, 0x6f, 0x6f,
	0x6b, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x62, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2e, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x62, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x16, 0x5a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x63,
	0x68, 0x65, 0x63, 0x6b, 0x62, 0x6f, 0x6f, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_checkbook_proto_rawDescOnce sync.Once
	file_checkbook_proto_rawDescData = file_checkbook_proto_rawDesc
)

func file_checkbook_proto_rawDescGZIP() []byte {
	file_checkbook_proto_rawDescOnce.Do(func() {
		file_checkbook_proto_rawDescData = protoimpl.X.CompressGZIP(file_checkbook_proto_rawDescData)
	})
	return file_checkbook_proto_rawDescData
}

var file_checkbook_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_checkbook_proto_goTypes = []interface{}{
	(*CheckbookRequest)(nil),  // 0: protofiles.CheckbookRequest
	(*CheckbookResponse)(nil), // 1: protofiles.CheckbookResponse
}
var file_checkbook_proto_depIdxs = []int32{
	0, // 0: protofiles.CheckbookService.CreateCheckbook:input_type -> protofiles.CheckbookRequest
	1, // 1: protofiles.CheckbookService.CreateCheckbook:output_type -> protofiles.CheckbookResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_checkbook_proto_init() }
func file_checkbook_proto_init() {
	if File_checkbook_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_checkbook_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckbookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_checkbook_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckbookResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_checkbook_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_checkbook_proto_goTypes,
		DependencyIndexes: file_checkbook_proto_depIdxs,
		MessageInfos:      file_checkbook_proto_msgTypes,
	}.Build()
	File_checkbook_proto = out.File
	file_checkbook_proto_rawDesc = nil
	file_checkbook_proto_goTypes = nil
	file_checkbook_proto_depIdxs = nil
}
